language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
  - mongodb

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USER" --password-stdin registry.heroku.com

before_script:
  - npm install
script:
  - docker build -t backsiembra .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag backsiembra $DOCKER_USER/backsiembra:$TRAVIS_BUILD_NUMBER
    docker tag jpmosquera/backsiembra registry.heroku.com/$HEROKU_APP_NAME/web
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
  - docker push $DOCKER_USER/backsiembra:$TRAVIS_BUILD_NUMBER
  - docker tag backsiembra $DOCKER_USER/backsiembra:latest
  - docker push $DOCKER_USER/backsiembra:latest

deploy:
  provider: script
  script: 
    # push to dockerhub & heroku
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
